schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.6"
    import: ["@external", "@key", "@requires", "@shareable", "@tag", "FieldSet"]
  ) {
  query: Query
}

type Query {
  _service: _Service!
  _entities(representations: [_Any!]!): [_Entity]!
}

type Money @shareable {
  amount: Decimal!
  currency: String!
}

type Product @key(fields: "id") {
  price: Money!
  shippingCost: Money! @requires(fields: "category")
  id: ID!
  category: ProductCategory! @external
}

"This type provides a field named sdl: String! which exposes the SDL of the service's schema. This SDL (schema definition language) is a printed version of the service's schema including the annotations of federation directives. This SDL does not include the additions of the federation spec."
type _Service {
  sdl: String!
}

"Union of all types that key directive applied. This information is needed by the Apollo federation gateway."
union _Entity = Product

"Defines when a policy shall be executed."
enum ApplyPolicy {
  "Before the resolver was executed."
  BEFORE_RESOLVER
  "After the resolver was executed."
  AFTER_RESOLVER
  "The policy is applied in the validation step before the execution."
  VALIDATION
}

enum ProductCategory {
  FURNITURE
  LIGHTING
  KITCHEN
  TEXTILES
  STORAGE
}

"The `Decimal` scalar type represents a decimal floating-point number with high precision."
scalar Decimal
  @specifiedBy(url: "https://scalars.graphql.org/chillicream/decimal.html")

"Scalar representing a set of fields."
scalar FieldSet

"The _Any scalar is used to pass representations of entities from external services into the root _entities field for execution. Validation of the _Any scalar is done by matching the __typename and @external fields defined in the schema."
scalar _Any

"Directive to indicate that a field is owned by another service, for example via Apollo federation."
directive @external on OBJECT | FIELD_DEFINITION

"Used to indicate a combination of fields that can be used to uniquely identify and fetch an object or interface."
directive @key(fields: FieldSet!, resolvable: Boolean = true) repeatable on
  | OBJECT
  | INTERFACE

"Links definitions within the document to external schemas."
directive @link(
  "Gets imported specification url."
  url: String!
  "Gets optional list of imported element names."
  import: [String!]
) repeatable on SCHEMA

"Used to annotate the required input fieldset from a base type for a resolver."
directive @requires(fields: FieldSet!) on FIELD_DEFINITION

"Indicates that given object and/or field can be resolved by multiple subgraphs."
directive @shareable repeatable on OBJECT | FIELD_DEFINITION
